---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -d '{ignore: "../../hosts.yml"}' .
  ansible-lint -r bug
  flake8
platforms:
  - name: multiple-host
    groups:
      - example
    children:
      - oracle
      - monitor
      - ui
    image: ubuntu:16.04
    privileged: true
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
  playbooks:
    prepare: ../prepare.yml
    converge: ../monitor/converge.yml
  inventory:
    host_vars:
      multiple-host:
        ORACLE_VALIDATOR_ADDRESS_PRIVATE_KEY: "8e829f695aed89a154550f30262f1529582cc49dc30eff74a6b491359e0230f9"
        MONITOR_PORT: 3003
        syslog_server_port: "udp://127.0.0.1:514"
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ../../tests/*
scenario:
  name: multiple
  test_sequence:
    - lint
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
